import './js/weather-section';
import './js/header';
import './js/news';
// import './js/them-toggle';
import './js/input-serch-fetch-news';
import './js/calendar';
// import './js/mobile-menu';
import './js/pagination';
import './js/category-search-list';
import './js/page-favorite';
// import './js/weather-section';
